# github-pages mandatory configuration
domain: makemebitter.github.com
url: https://makemebitter.github.com/
baseurl: /DeepPostures/
repository: makemebitter/DeepPostures


remote_theme: just-the-docs/just-the-docs
